# Generated by Django 3.1.2 on 2021-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default='440dd5b05dc844d5824d79def1092859', editable=False, unique=True)),
                ('category', models.CharField(choices=[('KYC issue', 'kyc'), ('Balance Receive', 'transaction_1'), ('Balance Forward', 'transaction_2'), ('Password and account access', 'user_security'), ('Business Solutions', 'operational')], max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('resolve', 'resolve'), ('reopen', 'reopen')], default='pending', max_length=16)),
                ('user_id', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_user_message', models.BooleanField(default=0)),
                ('is_admin_message', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
