# Generated by Django 3.1.2 on 2021-05-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210509_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='uuid',
            field=models.UUIDField(default='d1b658bfc1494e4d81f4ee46eb76deb5', editable=False, unique=True),
        ),
    ]
