# Generated by Django 3.1.2 on 2021-05-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_0935'),
        ('app', '0003_auto_20210509_1553'),
    ]

    operations = [
    ]
