# Generated by Django 3.1.2 on 2021-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='uuid',
            field=models.UUIDField(default='06c5415ebb0f48ae9839841f7f481830', editable=False, unique=True),
        ),
    ]
