# Generated by Django 3.1.2 on 2021-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20210509_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='uuid',
            field=models.CharField(max_length=50),
        ),
    ]
