# Generated by Django 3.1.2 on 2021-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210509_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='uuid',
            field=models.UUIDField(default='cb0f42a7d03c4e85879a8dd29ce1dff7', editable=False, unique=True),
        ),
    ]
