# Generated by Django 3.1.2 on 2021-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210509_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='uuid',
            field=models.UUIDField(default='7d2fbdf5ab7b4901942cbe3ae9164f00', editable=False, unique=True),
        ),
    ]
