# Generated by Django 3.1.2 on 2021-05-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20210509_1558'),
        ('app', '0005_auto_20210509_1556'),
    ]

    operations = [
    ]
