# Generated by Django 3.1.2 on 2021-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20210509_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('resident', models.CharField(blank=True, max_length=40)),
                ('verification_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('liscense', 'Liscense')], max_length=40)),
                ('id_number', models.IntegerField(blank=True)),
                ('identification_verification_front', models.TextField()),
                ('identification_verification_back', models.TextField()),
                ('hand_held_identification', models.TextField()),
                ('status', models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
