# Generated by Django 3.1.2 on 2021-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_kycmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmanagement',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
