# Generated by Django 3.1.2 on 2021-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_kycmanagement_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmanagement',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
