# Generated by Django 3.1.2 on 2021-06-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_kycmanagement_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmanagement',
            name='id_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
