# Generated by Django 3.1.2 on 2021-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210728_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('KYC', 'KYC'), ('SUPPORT_TICKET', 'SUPPORT_TICKET'), ('CHAT', 'CHAT'), ('', '')], default='', max_length=24),
        ),
    ]
