# Generated by Django 3.1.2 on 2021-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kyc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
