# Generated by Django 3.1.2 on 2021-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notification_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
