# Generated by Django 3.1.2 on 2021-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_notification_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmanagement',
            name='deleted',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
